name: CD (development)

on:
  push:
    branches: [develop]
    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    strategy:
      matrix:
        node-version: [14.17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install deps...
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          alias: develop
          publish-dir: './dist'
          production-branch: master
          production-deploy: false
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
          deploy-message: ${{ github.sha }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
